- hosts: test
  tasks:
  - debug:
     msg: "I'm in group 'test'"


- name: lockdown using CIS
  hosts: cissecure

  vars:
    is_container: false

  roles:
  - role: cissecure
    ubtu20cis_system_is_container: "{{ is_container | default(false) }}"
    ubtu20cis_skip_for_travis: false
    ubtu20cis_oscap_scan: yes

- name: deploy webserver container
  hosts: webserver
  roles:
  - role: galaxyinstall
  - role: webserver

# - name: configure ansible-pull
#   hosts: none
#   roles:
#   - role: ansible-pull
#     ansible_pull:
#       url: https://github.com/leicynad/tsc-ansible-example.git
