---

- name: installing podman
  package:
    name: "podman"
    state: present

- name: add registry
  lineinfile:
    path: /etc/containers/registries.conf
    regexp: '^unqualified-search-registries.*'
    insertafter: '^# unqualified-search-registries.*'
    line: 'unqualified-search-registries=["docker.io"]'

- name: Pull an image
  containers.podman.podman_image:
    name: httpd

- name: Creates directory
  file:
    path: /var/www
    state: directory

- name: Add Keepalived config file
  template:
    dest: /var/www/index.html
    src: index.html.j2

- name: create test container
  containers.podman.podman_container:
    name: testcontainer
    image: httpd
    state: started
    detach: true
    exposed_ports:
      - 80
    ports:
      - 80:80
    volumes: /var/www/:/usr/local/apache2/htdocs/
