---

- name: galaxyroles path
  file:
    path:  galaxyroles
    state: absent

- name: launch galaxy role install
  delegate_to: localhost
  command: command ansible-galaxy role install -r requirements.yml

- name: gitignore galaxy role
  lineinfile:
    dest:   .gitignore
    regexp: '^\/galaxyroles$'
    line:   '/galaxyroles'
    state:  present

- name: ansible collection path
  file:
    path: ansible_collections
    state: absent

- name: launch galaxy collection install
  delegate_to: localhost
  command: command ansible-galaxy collection install -r requirements.yml

- name: gitignore galaxy collection
  lineinfile:
    dest:   .gitignore
    regexp: '^\/ansible_collections$'
    line:   '/ansible_collections'
    state:  present
